### ISSUE TITLE
Acceptance Testing Week 11

### ISSUE THREAD

**Issue by cjianhui** [CS2103AUG2017-T16-B2/main#102]
![schedule problem t16](https://user-images.githubusercontent.com/31098608/32363291-942175e0-c0a9-11e7-8b8a-b691ae13212f.PNG)
![schedule problem 2 t16](https://user-images.githubusercontent.com/31098608/32363292-9456f7f6-c0a9-11e7-8541-a677d3013ed0.PNG)

Validation for schedule adding may be buggy.

**Comment by hanselblack** [comment]
![image](https://user-images.githubusercontent.com/29362659/32363410-3a1499a0-c0aa-11e7-89d3-4ccbe5b815e5.png)

Sorry, but I cannot add the schedule too.

**Comment by jeffreygohkw** [comment]
Help:
As a new user, when the help window is open, when I perform commands, it doesn't update in the UI until I close the help window, this is very inconvenient and I have to open the help window every time after each command.

UI:
Your graph is far too small on my computer, I cannot resize it or see anything about it. I also don't think a graph is the way to go to display the information you want, as the students are not in a sequential order.
![image](https://user-images.githubusercontent.com/20789829/32363713-8eee8a66-c0ab-11e7-8536-89c272a69542.png)

The column in between the person's details and the graph has no data displayed on launch, and shows stuff like $mode, $standarddeviation etc. Is this a bug? Contrast is pretty poor and it is hard to see too. It ended up updating afterwards somehow. Is it supposed to display the statistics for the entire list of persons or the class? It is not very clear, so  I suggest not using Group, or elaborate in the User Guide.

The bottom half of the screen on the 2nd, 3rd and 4th columns is blank, maybe have something there so you don't waste screen real estate.

find, findtags and clear
Using the command `find debate` or `clear` gives a white box in the first column.

schedule:
Scheduling a person doesn't seem to do anything at all. Where can I see the schedule list?

edit:
I can't edit a person's phone or a parent's phone alone and I am forced to update them both

**Comment by lincredibleJC** [comment]
Thanks for the feedback guys.

We have looked at the bug reports and suggestions and fixed them, the changes will be reflected in the next version v1.5rc.
