### ISSUE TITLE
Scheduling feature is buggy when entering invalid times

### ISSUE THREAD

**Issue by lincredibleJC** [CS2103AUG2017-T16-B2/main#109]
Referenced from #102 

Validation for schedule adding may be buggy

![schedule problem t16](https://user-images.githubusercontent.com/31098608/32363291-942175e0-c0a9-11e7-8b8a-b691ae13212f.PNG)
![schedule problem 2 t16](https://user-images.githubusercontent.com/31098608/32363292-9456f7f6-c0a9-11e7-8541-a677d3013ed0.PNG)

**Comment by limcel** [comment]
#133 added relevant notes in UserGuide.
