### ISSUE TITLE
Unable to use scheduling feature, shows Unknown command

### ISSUE THREAD

**Issue by lincredibleJC** [CS2103AUG2017-T16-B2/main#110]
Referenced from #102

![image](https://user-images.githubusercontent.com/29362659/32363410-3a1499a0-c0aa-11e7-89d3-4ccbe5b815e5.png)

Sorry, but I cannot add the schedule too.list?

**Comment by limcel** [comment]
#closed. The person used the wrong version of cherBook. Scheduling only available in v1.4 but user is using v1.3.
