### ISSUE TITLE
Sorting undoes the find / findtags command

### ISSUE THREAD

**Issue by lincredibleJC** [CS2103AUG2017-T16-B2/main#136]
The sort feature undoes the list of students from the find / findtags commands

Steps to replicate:
- Open cherBook
- Execute `findtags studentcouncil`
- Execute `sort`
- Then all students are shown in the address book again

![image](https://user-images.githubusercontent.com/22949932/32688220-f324adfa-c707-11e7-9599-a575b52da972.png)
`findtags student council` executed, list size is 12.

![image](https://user-images.githubusercontent.com/22949932/32688227-04ea678c-c708-11e7-9337-de63231ee35f.png)
`sort` executed, list size back to 40.

**Comment by limcel** [comment]
This is not a bug it is my implementation of the sort command. Read [this](https://github.com/lincredibleJC/main/blob/feature/Update_DeveloperGuide/docs/DeveloperGuide.adoc#46-sort-mechanism) to understand my reason behind this command.
